# Generated by Django 4.2.4 on 2023-08-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('New', 'Brand New'), ('Good', 'Good'), ('Untested', 'Untested'), ('Bad', 'Bad')], max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('quantity', models.CharField(max_length=250)),
                ('inventory_img', models.ImageField(upload_to='image')),
            ],
        ),
    ]
