# Generated by Django 4.2.2 on 2023-08-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_img',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
