# Generated by Django 4.2.4 on 2023-08-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date_of_action',
            field=models.DateField(blank=True, null=True),
        ),
    ]
