# Generated by Django 4.2.2 on 2023-08-28 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_alter_inventory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_repaired', models.CharField(max_length=250)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('mechanic_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('mechanic_Number', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_spent', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('supervised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
