# Generated by Django 4.2.2 on 2023-08-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='date',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
