# Generated by Django 4.2.2 on 2023-08-28 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('crew', models.TextField(blank=True, null=True)),
                ('expected_Days_of_completion', models.PositiveIntegerField()),
                ('actual_Days_of_completion', models.PositiveIntegerField(blank=True, null=True)),
                ('survey_lithology', models.FileField(upload_to='')),
                ('drilling_plan', models.FileField(upload_to='')),
                ('casing_plan', models.FileField(upload_to='')),
                ('supervised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
