# Generated by Django 4.2.2 on 2023-08-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='record_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='casing_plan',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
