# Generated by Django 4.2.2 on 2023-08-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='record_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
