# Generated by Django 4.2.4 on 2023-08-31 16:26

import django.core.validators
from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_record_date_alter_job_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='casing_plan',
            field=models.FileField(blank=True, null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx']), job.models.validate_file_mimetype]),
        ),
        migrations.AlterField(
            model_name='job',
            name='drilling_plan',
            field=models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx']), job.models.validate_file_mimetype]),
        ),
        migrations.AlterField(
            model_name='job',
            name='survey_lithology',
            field=models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx']), job.models.validate_file_mimetype]),
        ),
    ]
